#!/usr/bin/env python3
"""
🏗️ Landing Page Blueprint Generator
=====================================
Generates premium landing pages from JSON configs.
Same design system as the live BMA consulting page.

Usage:
    python blueprints/generate_landing.py blueprints/configs/bma_consulting.json --output consulting/
    python blueprints/generate_landing.py blueprints/configs/ai_coaching.json --output ai-coaching/
"""

import json
import sys
import os
import argparse
from urllib.parse import quote


def load_config(path: str) -> dict:
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f)


def format_price(price: int) -> str:
    """Format price with dot separator for thousands (German style)."""
    if price >= 1000:
        return f"€{price:,}".replace(",", ".")
    return f"€{price}"


def build_paypal_url(email: str, amount: int, item_name: str, currency: str = "EUR") -> str:
    return (
        f"https://www.paypal.com/cgi-bin/webscr?cmd=_xclick"
        f"&business={quote(email)}"
        f"&currency_code={currency}"
        f"&amount={amount}"
        f"&item_name={quote(item_name)}"
    )


def generate_css(cfg: dict) -> str:
    brand = cfg["brand"]
    accent = brand.get("accent_color", "#f97316")
    accent_light = brand.get("accent_light", "#fb923c")
    secondary = brand.get("secondary_glow", "#6366f1")

    return f"""
        /* ============================================
           DESIGN SYSTEM — Generated by Blueprint Engine
           ============================================ */
        :root {{
            --bg-primary: #0a0a0f;
            --bg-secondary: #12121a;
            --bg-card: #1a1a28;
            --bg-card-hover: #22223a;
            --accent: {accent};
            --accent-light: {accent_light};
            --accent-glow: rgba({_hex_to_rgb(accent)}, 0.15);
            --accent-glow-strong: rgba({_hex_to_rgb(accent)}, 0.3);
            --green: #22c55e;
            --green-glow: rgba(34, 197, 94, 0.15);
            --red: #ef4444;
            --text-primary: #f1f1f4;
            --text-secondary: #a1a1b5;
            --text-muted: #6b6b80;
            --border: #2a2a3d;
            --border-accent: rgba({_hex_to_rgb(accent)}, 0.3);
            --radius: 16px;
            --radius-sm: 10px;
        }}

        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        html {{ scroll-behavior: smooth; }}

        body {{
            font-family: 'Inter', system-ui, -apple-system, sans-serif;
            background: var(--bg-primary);
            color: var(--text-primary);
            line-height: 1.7;
            overflow-x: hidden;
        }}

        .bg-glow {{
            position: fixed; width: 600px; height: 600px;
            border-radius: 50%; filter: blur(150px); opacity: 0.07;
            pointer-events: none; z-index: 0;
        }}
        .bg-glow-1 {{ top: -200px; left: -200px; background: var(--accent); }}
        .bg-glow-2 {{ bottom: -200px; right: -200px; background: {secondary}; }}

        .container {{
            max-width: 1100px; margin: 0 auto;
            padding: 0 1.5rem; position: relative; z-index: 1;
        }}
        section {{ padding: 5rem 0; }}

        /* NAV */
        nav {{
            position: fixed; top: 0; left: 0; right: 0;
            background: rgba(10, 10, 15, 0.85);
            backdrop-filter: blur(20px);
            border-bottom: 1px solid var(--border);
            z-index: 100; padding: 1rem 0;
        }}
        nav .container {{ display: flex; justify-content: space-between; align-items: center; }}
        .nav-brand {{ font-weight: 800; font-size: 1.1rem; color: var(--accent); letter-spacing: -0.5px; }}
        .nav-cta {{
            background: var(--accent); color: #fff;
            padding: 0.6rem 1.5rem; border-radius: 50px;
            text-decoration: none; font-weight: 700; font-size: 0.85rem;
            letter-spacing: 0.5px; transition: all 0.3s ease; text-transform: uppercase;
        }}
        .nav-cta:hover {{
            background: var(--accent-light); transform: translateY(-2px);
            box-shadow: 0 8px 25px rgba({_hex_to_rgb(accent)}, 0.4);
        }}

        /* HERO */
        .hero {{ padding: 10rem 0 6rem; text-align: center; }}
        .hero-badge {{
            display: inline-block; background: var(--accent-glow);
            border: 1px solid var(--border-accent); color: var(--accent);
            padding: 0.5rem 1.2rem; border-radius: 50px;
            font-size: 0.8rem; font-weight: 700; letter-spacing: 1.5px;
            text-transform: uppercase; margin-bottom: 2rem;
            animation: pulse-badge 2s ease-in-out infinite;
        }}
        @keyframes pulse-badge {{
            0%, 100% {{ box-shadow: 0 0 0 0 rgba({_hex_to_rgb(accent)}, 0.3); }}
            50% {{ box-shadow: 0 0 0 8px rgba({_hex_to_rgb(accent)}, 0); }}
        }}
        .hero h1 {{
            font-size: clamp(2.5rem, 6vw, 4.2rem); font-weight: 900;
            line-height: 1.1; letter-spacing: -2px; margin-bottom: 1.5rem;
        }}
        .hero h1 .highlight {{
            background: linear-gradient(135deg, var(--accent), #f59e0b);
            -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text;
        }}
        .hero-sub {{
            font-size: 1.25rem; color: var(--text-secondary);
            max-width: 650px; margin: 0 auto 3rem; line-height: 1.8;
        }}
        .hero-stats {{ display: flex; justify-content: center; gap: 3rem; margin-top: 3rem; flex-wrap: wrap; }}
        .hero-stat {{ text-align: center; }}
        .hero-stat-number {{ font-size: 2.5rem; font-weight: 900; color: var(--accent); }}
        .hero-stat-label {{ font-size: 0.85rem; color: var(--text-muted); text-transform: uppercase; letter-spacing: 1px; }}

        /* CTA BUTTONS */
        .cta-primary {{
            display: inline-block;
            background: linear-gradient(135deg, var(--accent), #ea580c);
            color: #fff; padding: 1.2rem 3rem; border-radius: 50px;
            text-decoration: none; font-weight: 800; font-size: 1.15rem;
            letter-spacing: 0.5px; transition: all 0.3s ease;
            box-shadow: 0 8px 30px rgba({_hex_to_rgb(accent)}, 0.35);
            position: relative; overflow: hidden;
        }}
        .cta-primary::after {{
            content: ''; position: absolute; top: -50%; left: -60%;
            width: 200%; height: 200%;
            background: linear-gradient(90deg, transparent, rgba(255,255,255,0.1), transparent);
            transform: rotate(25deg); animation: shine 3s ease-in-out infinite;
        }}
        @keyframes shine {{ 0% {{ left: -60%; }} 50% {{ left: 100%; }} 100% {{ left: 100%; }} }}
        .cta-primary:hover {{
            transform: translateY(-3px);
            box-shadow: 0 15px 40px rgba({_hex_to_rgb(accent)}, 0.5);
        }}

        /* PAIN SECTION */
        .pain-section {{
            background: var(--bg-secondary);
            border-top: 1px solid var(--border); border-bottom: 1px solid var(--border);
        }}
        .pain-section h2 {{ font-size: 2rem; font-weight: 800; margin-bottom: 0.5rem; text-align: center; }}
        .pain-section .section-sub {{ color: var(--text-secondary); text-align: center; margin-bottom: 3rem; font-size: 1.1rem; }}
        .pain-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 1.5rem; }}
        .pain-card {{
            background: var(--bg-card); border: 1px solid var(--border);
            border-radius: var(--radius); padding: 2rem; transition: all 0.3s ease;
        }}
        .pain-card:hover {{ border-color: var(--red); transform: translateY(-3px); }}
        .pain-icon {{ font-size: 2rem; margin-bottom: 1rem; }}
        .pain-card h3 {{ font-size: 1.1rem; font-weight: 700; margin-bottom: 0.5rem; }}
        .pain-card p {{ color: var(--text-secondary); font-size: 0.95rem; }}
        .pain-cost {{ color: var(--red); font-weight: 700; font-size: 0.9rem; margin-top: 0.75rem; }}

        /* SECTION HEADERS */
        .section-header {{ text-align: center; margin-bottom: 3.5rem; }}
        .section-header h2 {{ font-size: 2.2rem; font-weight: 800; letter-spacing: -1px; margin-bottom: 0.75rem; }}
        .section-header p {{ color: var(--text-secondary); font-size: 1.1rem; max-width: 600px; margin: 0 auto; }}

        /* PRICING */
        .pricing-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(320px, 1fr)); gap: 2rem; align-items: stretch; }}
        .pricing-card {{
            background: var(--bg-card); border: 1px solid var(--border);
            border-radius: var(--radius); padding: 2.5rem 2rem;
            display: flex; flex-direction: column; transition: all 0.4s ease;
            position: relative; overflow: hidden;
        }}
        .pricing-card:hover {{
            border-color: var(--border-accent); transform: translateY(-5px);
            box-shadow: 0 20px 60px rgba(0,0,0,0.3);
        }}
        .pricing-card.featured {{ border-color: var(--accent); box-shadow: 0 0 40px var(--accent-glow); }}
        .pricing-card.featured::before {{
            content: attr(data-featured-label);
            position: absolute; top: 0; left: 0; right: 0;
            background: linear-gradient(135deg, var(--accent), #ea580c);
            color: #fff; text-align: center; padding: 0.5rem;
            font-size: 0.75rem; font-weight: 800; letter-spacing: 2px;
        }}
        .pricing-card.featured {{ padding-top: 3.5rem; }}
        .pricing-tier {{ font-size: 0.8rem; font-weight: 700; letter-spacing: 2px; text-transform: uppercase; color: var(--accent); margin-bottom: 0.5rem; }}
        .pricing-name {{ font-size: 1.5rem; font-weight: 800; margin-bottom: 0.5rem; }}
        .pricing-desc {{ color: var(--text-secondary); font-size: 0.9rem; margin-bottom: 1.5rem; }}
        .pricing-price {{ font-size: 3.5rem; font-weight: 900; margin-bottom: 0.25rem; }}
        .pricing-price span {{ font-size: 1rem; font-weight: 500; color: var(--text-muted); }}
        .pricing-value {{ color: var(--green); font-size: 0.85rem; font-weight: 600; margin-bottom: 2rem; display: flex; align-items: center; gap: 0.4rem; }}
        .pricing-features {{ list-style: none; margin-bottom: 2rem; flex-grow: 1; }}
        .pricing-features li {{ padding: 0.6rem 0; font-size: 0.95rem; color: var(--text-secondary); display: flex; align-items: flex-start; gap: 0.75rem; }}
        .pricing-features li::before {{ content: '✓'; color: var(--green); font-weight: 700; flex-shrink: 0; }}
        .pricing-cta {{
            display: block; text-align: center; padding: 1rem;
            border-radius: var(--radius-sm); text-decoration: none;
            font-weight: 700; font-size: 1rem; transition: all 0.3s ease; letter-spacing: 0.5px;
        }}
        .pricing-cta-primary {{
            background: linear-gradient(135deg, var(--accent), #ea580c); color: #fff;
            box-shadow: 0 5px 20px rgba({_hex_to_rgb(accent)}, 0.3);
        }}
        .pricing-cta-primary:hover {{ transform: translateY(-2px); box-shadow: 0 10px 30px rgba({_hex_to_rgb(accent)}, 0.5); }}
        .pricing-cta-secondary {{ background: transparent; color: var(--accent); border: 2px solid var(--accent); }}
        .pricing-cta-secondary:hover {{ background: var(--accent-glow); }}

        /* AUTHORITY */
        .authority {{ background: var(--bg-secondary); border-top: 1px solid var(--border); border-bottom: 1px solid var(--border); }}
        .authority-content {{ display: grid; grid-template-columns: 1fr 1fr; gap: 4rem; align-items: center; }}
        .authority-text h2 {{ font-size: 2rem; font-weight: 800; margin-bottom: 1.5rem; line-height: 1.2; }}
        .authority-text p {{ color: var(--text-secondary); margin-bottom: 1rem; font-size: 1.05rem; }}
        .authority-badges {{ display: flex; flex-direction: column; gap: 1rem; }}
        .authority-badge {{
            background: var(--bg-card); border: 1px solid var(--border);
            border-radius: var(--radius-sm); padding: 1.25rem 1.5rem;
            display: flex; align-items: center; gap: 1rem; transition: all 0.3s ease;
        }}
        .authority-badge:hover {{ border-color: var(--border-accent); transform: translateX(5px); }}
        .authority-badge-icon {{ font-size: 1.8rem; flex-shrink: 0; }}
        .authority-badge-text h4 {{ font-weight: 700; font-size: 1rem; }}
        .authority-badge-text p {{ color: var(--text-muted); font-size: 0.85rem; margin: 0; }}

        /* GUARANTEE */
        .guarantee {{ text-align: center; }}
        .guarantee-box {{
            background: var(--bg-card); border: 2px solid var(--green);
            border-radius: var(--radius); padding: 3rem; max-width: 700px;
            margin: 0 auto; box-shadow: 0 0 40px var(--green-glow);
        }}
        .guarantee-icon {{ font-size: 3rem; margin-bottom: 1rem; }}
        .guarantee-box h2 {{ font-size: 1.8rem; font-weight: 800; margin-bottom: 1rem; }}
        .guarantee-box p {{ color: var(--text-secondary); font-size: 1.05rem; max-width: 500px; margin: 0 auto; }}

        /* FAQ */
        .faq-list {{ max-width: 750px; margin: 0 auto; }}
        .faq-item {{ border-bottom: 1px solid var(--border); padding: 1.5rem 0; }}
        .faq-question {{
            font-weight: 700; font-size: 1.05rem; cursor: pointer;
            display: flex; justify-content: space-between; align-items: center; transition: color 0.3s;
        }}
        .faq-question:hover {{ color: var(--accent); }}
        .faq-question::after {{ content: '+'; font-size: 1.5rem; color: var(--accent); transition: transform 0.3s; }}
        .faq-item.active .faq-question::after {{ transform: rotate(45deg); }}
        .faq-answer {{ max-height: 0; overflow: hidden; transition: max-height 0.3s ease, padding 0.3s ease; color: var(--text-secondary); font-size: 0.95rem; }}
        .faq-item.active .faq-answer {{ max-height: 200px; padding-top: 1rem; }}

        /* FINAL CTA */
        .final-cta {{ text-align: center; padding: 6rem 0; background: linear-gradient(180deg, var(--bg-primary), var(--bg-secondary)); }}
        .final-cta h2 {{ font-size: 2.5rem; font-weight: 900; margin-bottom: 1rem; letter-spacing: -1px; }}
        .final-cta p {{ color: var(--text-secondary); font-size: 1.15rem; margin-bottom: 2.5rem; max-width: 550px; margin-left: auto; margin-right: auto; }}
        .scarcity-badge {{
            display: inline-block; background: rgba(239, 68, 68, 0.1);
            border: 1px solid rgba(239, 68, 68, 0.3); color: var(--red);
            padding: 0.5rem 1.2rem; border-radius: 50px;
            font-size: 0.85rem; font-weight: 700; margin-top: 1.5rem;
            animation: pulse-badge 2s ease-in-out infinite;
        }}

        /* FOOTER */
        footer {{ border-top: 1px solid var(--border); padding: 3rem 0; text-align: center; color: var(--text-muted); font-size: 0.85rem; }}
        footer a {{ color: var(--text-secondary); text-decoration: none; transition: color 0.2s; }}
        footer a:hover {{ color: var(--accent); }}
        .footer-links {{ display: flex; justify-content: center; gap: 2rem; margin-bottom: 1.5rem; flex-wrap: wrap; }}

        /* MODAL */
        .modal-overlay {{
            display: none; position: fixed; top: 0; left: 0; right: 0; bottom: 0;
            background: rgba(0,0,0,0.8); z-index: 200;
            justify-content: center; align-items: center; padding: 2rem;
        }}
        .modal-overlay.active {{ display: flex; }}
        .modal-content {{
            background: var(--bg-card); border: 1px solid var(--border);
            border-radius: var(--radius); padding: 2.5rem; max-width: 600px;
            width: 100%; max-height: 80vh; overflow-y: auto; position: relative;
        }}
        .modal-close {{ position: absolute; top: 1rem; right: 1rem; background: none; border: none; color: var(--text-muted); font-size: 1.5rem; cursor: pointer; }}
        .modal-content h2 {{ font-size: 1.5rem; margin-bottom: 1.5rem; }}
        .modal-content p {{ color: var(--text-secondary); margin-bottom: 0.75rem; font-size: 0.95rem; }}

        /* RESPONSIVE */
        @media (max-width: 768px) {{
            .hero {{ padding: 8rem 0 4rem; }}
            .hero h1 {{ font-size: 2.2rem; letter-spacing: -1px; }}
            .hero-sub {{ font-size: 1.05rem; }}
            .hero-stats {{ gap: 1.5rem; }}
            .hero-stat-number {{ font-size: 2rem; }}
            .authority-content {{ grid-template-columns: 1fr; gap: 2rem; }}
            .pricing-grid {{ grid-template-columns: 1fr; }}
            section {{ padding: 3.5rem 0; }}
            .guarantee-box {{ padding: 2rem; }}
            .final-cta h2 {{ font-size: 1.8rem; }}
        }}

        /* ANIMATIONS */
        .fade-in {{ opacity: 0; transform: translateY(30px); transition: opacity 0.6s ease, transform 0.6s ease; }}
        .fade-in.visible {{ opacity: 1; transform: translateY(0); }}
    """


def _hex_to_rgb(hex_color: str) -> str:
    """Convert #f97316 to '249, 115, 22'."""
    h = hex_color.lstrip('#')
    return f"{int(h[0:2], 16)}, {int(h[2:4], 16)}, {int(h[4:6], 16)}"


def generate_html(cfg: dict) -> str:
    seo = cfg["seo"]
    brand = cfg["brand"]
    nav = cfg["nav"]
    hero = cfg["hero"]
    pain = cfg["pain"]
    pricing = cfg["pricing"]
    authority = cfg["authority"]
    guarantee = cfg["guarantee"]
    faq = cfg["faq"]
    final = cfg["final_cta"]
    footer = cfg["footer"]

    # --- Build sections ---
    stats_html = "\n".join(
        f'<div class="hero-stat"><div class="hero-stat-number">{s["number"]}</div>'
        f'<div class="hero-stat-label">{s["label"]}</div></div>'
        for s in hero["stats"]
    )

    pain_cards = "\n".join(
        f'''<div class="pain-card fade-in">
    <div class="pain-icon">{c["icon"]}</div>
    <h3>{c["title"]}</h3>
    <p>{c["text"]}</p>
    <div class="pain-cost">{c["cost"]}</div>
</div>'''
        for c in pain["cards"]
    )

    pricing_cards = "\n".join(_build_pricing_card(t, brand) for t in pricing["tiers"])

    authority_paragraphs = "\n".join(f"<p>{p}</p>" for p in authority["paragraphs"])
    authority_badges = "\n".join(
        f'''<div class="authority-badge">
    <div class="authority-badge-icon">{b["icon"]}</div>
    <div class="authority-badge-text">
        <h4>{b["title"]}</h4>
        <p>{b["text"]}</p>
    </div>
</div>'''
        for b in authority["badges"]
    )

    faq_items = "\n".join(
        f'''<div class="faq-item fade-in">
    <div class="faq-question">{q["question"]}</div>
    <div class="faq-answer">{q["answer"]}</div>
</div>'''
        for q in faq
    )

    imp = footer["impressum"]

    css = generate_css(cfg)

    return f'''<!DOCTYPE html>
<html lang="{seo.get("lang", "de")}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{seo["title"]}</title>
    <meta name="description" content="{seo["meta_description"]}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap" rel="stylesheet">
    <style>{css}
    </style>
</head>
<body>

    <!-- Background Glows -->
    <div class="bg-glow bg-glow-1"></div>
    <div class="bg-glow bg-glow-2"></div>

    <!-- NAV -->
    <nav>
        <div class="container">
            <span class="nav-brand">{brand["name"]}</span>
            <a href="{nav["cta_anchor"]}" class="nav-cta">{nav["cta_text"]}</a>
        </div>
    </nav>

    <!-- HERO -->
    <section class="hero">
        <div class="container">
            <div class="hero-badge">{hero["badge"]}</div>
            <h1>{hero["headline_before"]}<span class="highlight">{hero["headline_highlight"]}</span><br>{hero["headline_after"]}</h1>
            <p class="hero-sub">{hero["subtext"]}</p>
            <a href="{hero["cta_anchor"]}" class="cta-primary" id="hero-cta">{hero["cta_text"]}</a>
            <div class="hero-stats fade-in">
                {stats_html}
            </div>
        </div>
    </section>

    <!-- PAIN SECTION -->
    <section class="pain-section">
        <div class="container">
            <h2 class="fade-in">{pain["title"]}</h2>
            <p class="section-sub fade-in">{pain["subtitle"]}</p>
            <div class="pain-grid">
                {pain_cards}
            </div>
        </div>
    </section>

    <!-- PRICING -->
    <section id="{pricing["anchor_id"]}">
        <div class="container">
            <div class="section-header fade-in">
                <h2>{pricing["section_title"]}</h2>
                <p>{pricing["section_subtitle"]}</p>
            </div>
            <div class="pricing-grid">
                {pricing_cards}
            </div>
        </div>
    </section>

    <!-- AUTHORITY -->
    <section class="authority">
        <div class="container">
            <div class="authority-content fade-in">
                <div class="authority-text">
                    <h2>{authority["title"]}</h2>
                    {authority_paragraphs}
                </div>
                <div class="authority-badges">
                    {authority_badges}
                </div>
            </div>
        </div>
    </section>

    <!-- GUARANTEE -->
    <section class="guarantee">
        <div class="container">
            <div class="guarantee-box fade-in">
                <div class="guarantee-icon">{guarantee["icon"]}</div>
                <h2>{guarantee["title"]}</h2>
                <p>{guarantee["text"]}</p>
            </div>
        </div>
    </section>

    <!-- FAQ -->
    <section>
        <div class="container">
            <div class="section-header fade-in">
                <h2>Häufige Fragen</h2>
            </div>
            <div class="faq-list">
                {faq_items}
            </div>
        </div>
    </section>

    <!-- FINAL CTA -->
    <section class="final-cta">
        <div class="container fade-in">
            <h2>{final["headline"]}</h2>
            <p>{final["subtext"]}</p>
            <a href="{final["cta_anchor"]}" class="cta-primary">{final["cta_text"]}</a>
            <br>
            <div class="scarcity-badge" id="scarcity-msg">{final["scarcity_text"].replace("{slots}", "5")}</div>
        </div>
    </section>

    <!-- FOOTER -->
    <footer>
        <div class="container">
            <div class="footer-links">
                <a href="mailto:{brand["contact_email"]}">✉️ {brand["contact_email"]}</a>
                <a href="#" onclick="document.getElementById('impressum-modal').classList.add('active'); return false;">Impressum</a>
            </div>
            <p>{footer["copyright"]}</p>
        </div>
    </footer>

    <!-- IMPRESSUM MODAL -->
    <div class="modal-overlay" id="impressum-modal">
        <div class="modal-content">
            <button class="modal-close" onclick="this.closest('.modal-overlay').classList.remove('active')">✕</button>
            <h2>Impressum</h2>
            <p><strong>{imp["name"]}</strong></p>
            <p>{imp["address"]}</p>
            <p>{imp["city"]}</p>
            <p><br><strong>Kontakt:</strong></p>
            <p>E-Mail: {brand["contact_email"]}</p>
            <p><br><strong>Hinweis:</strong></p>
            <p>{imp["note"]}</p>
        </div>
    </div>

    <!-- JAVASCRIPT -->
    <script>
        // FAQ Toggle
        document.querySelectorAll('.faq-question').forEach(q => {{
            q.addEventListener('click', () => {{
                const item = q.closest('.faq-item');
                item.classList.toggle('active');
            }});
        }});

        // Scroll Animations
        const observer = new IntersectionObserver((entries) => {{
            entries.forEach(entry => {{
                if (entry.isIntersecting) {{ entry.target.classList.add('visible'); }}
            }});
        }}, {{ threshold: 0.1, rootMargin: '0px 0px -50px 0px' }});
        document.querySelectorAll('.fade-in').forEach(el => observer.observe(el));

        // Scarcity Counter
        const scarcityEl = document.getElementById('scarcity-msg');
        if (scarcityEl) {{
            const today = new Date();
            const slotsLeft = Math.max(2, 5 - Math.floor(today.getDate() / 7));
            const template = `{final["scarcity_text"]}`;
            scarcityEl.textContent = template.replace('{{slots}}', slotsLeft);
        }}

        // Smooth scroll
        document.querySelectorAll('a[href^="#"]').forEach(a => {{
            a.addEventListener('click', e => {{
                e.preventDefault();
                const target = document.querySelector(a.getAttribute('href'));
                if (target) {{ target.scrollIntoView({{ behavior: 'smooth', block: 'start' }}); }}
            }});
        }});
    </script>

</body>
</html>'''


def _build_pricing_card(tier: dict, brand: dict) -> str:
    featured_class = " featured" if tier.get("featured") else ""
    featured_attr = f' data-featured-label="{tier.get("featured_label", "")}"' if tier.get("featured") else ""
    cta_class = "pricing-cta-primary" if tier.get("cta_style") == "primary" else "pricing-cta-secondary"
    paypal_url = build_paypal_url(brand["paypal_email"], tier["price"], tier["item_name"], brand.get("currency", "EUR"))

    features_html = "\n".join(f"<li>{f}</li>" for f in tier["features"])

    slug = tier["name"].lower().replace(" ", "")

    return f'''<div class="pricing-card{featured_class} fade-in"{featured_attr}>
    <div class="pricing-tier">{tier["tier_label"]}</div>
    <div class="pricing-name">{tier["name"]}</div>
    <div class="pricing-desc">{tier["description"]}</div>
    <div class="pricing-price">{format_price(tier["price"])} <span>{tier["price_suffix"]}</span></div>
    <div class="pricing-value">{tier["value_text"]}</div>
    <ul class="pricing-features">
        {features_html}
    </ul>
    <a href="{paypal_url}" class="pricing-cta {cta_class}" id="cta-{slug}">{tier["cta_text"]}</a>
</div>'''


def main():
    parser = argparse.ArgumentParser(description="🏗️ Landing Page Blueprint Generator")
    parser.add_argument("config", help="Path to JSON config file")
    parser.add_argument("--output", "-o", default="./output/", help="Output directory for generated index.html")
    args = parser.parse_args()

    cfg = load_config(args.config)
    html = generate_html(cfg)

    os.makedirs(args.output, exist_ok=True)
    output_path = os.path.join(args.output, "index.html")

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(html)

    print(f"✅ Generated: {output_path}")
    print(f"   Config:    {args.config}")
    print(f"   Title:     {cfg['seo']['title']}")
    print(f"   Tiers:     {len(cfg['pricing']['tiers'])} pricing packages")
    print(f"   Size:      {len(html):,} bytes")


if __name__ == "__main__":
    main()
